# yaml-language-server: $schema=https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json
$schema: "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
version: 4

blocks:
  - type: prompt
    alignment: left
    segments:
      - type: claude
        style: plain
        foreground: "#FF6B35"
        background: transparent
        template: >-
          󰯉 {{ .Model.DisplayName }}
          ◎ {{ .TokenUsagePercent.Gauge }} ({{ add .ContextWindow.TotalInputTokens .ContextWindow.TotalOutputTokens }})

        options:
          cache_duration: none
          gauge_marked_char: ●
          gauge_unmarked_char: ○
  - type: prompt
    alignment: left
    newline: true
    segments:
      - type: claude
        style: plain
        foreground: blue
        background: transparent
        template: "{{ .Workspace.CurrentDir }}"
  - type: prompt
    alignment: right
    segments:
      - type: git
        style: plain
        foreground: magenta
        background: transparent
        template: " {{ .HEAD }}"

        options:
          branch_icon: 

