#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'kubectl'
    style = 'plain'
    foreground = 'lightBlue'
    foreground_templates = ['{{if contains "prd" .Cluster}}red{{end}}']
    template = '{{ replaceP ".*/(.*)" .Cluster "$1" }} ⎈ {{if .Namespace}}{{.Namespace}}{{else}}default{{end}}'

  [[blocks.segments]]
    type = 'aws'
    style = 'plain'
    foreground = 'cyan'
    template = ' {{.Profile}}{{if .Region}} ☁  {{.Region}}{{end}}'

    [blocks.segments.properties]
      display_default = false


  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    background = 'transparent'
    foreground = 'blue'
    template = ' {{ .Path }}'

    [blocks.segments.properties]
      style = 'full'

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    foreground = 'magenta'
    template = ' {{ .HEAD }}{{if .Ahead }} ⇡{{ .Ahead }}{{ end }}{{if .Behind }} ⇣{{ .Behind }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }}{{ if .Working.Changed }} <yellow>{{ .Working.String }}</>{{ end }}{{ if .Staging.Changed }} <green>{{ .Staging.String }}</>{{ end }}'

    [blocks.segments.properties]
      fetch_status = true
      # branch_icon = ' '

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    type = 'executiontime'
    style = 'plain'
    foreground = 'yellow'
    background = 'transparent'
    template = '{{ .FormattedMs }}'

    [blocks.segments.properties]
      threshold = 5000

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground_templates = [
      "{{if gt .Code 0}}red{{end}}",
      "{{if eq .Code 0}}lightMagenta{{end}}",
    ]
    background = 'transparent'
    template = '❯'

[transient_prompt]
  foreground_templates = [
    "{{if gt .Code 0}}red{{end}}",
    "{{if eq .Code 0}}lightMagenta{{end}}",
  ]
  background = 'transparent'
  template = '❯ '

[secondary_prompt]
  foreground = 'lightMagenta'
  background = 'transparent'
  template = '❯❯ '
